add shfmt
Signed-off-by: Tonis Tiigi <tonistiigi@gmail.com>

diff --git a/base/xx-verify b/base/xx-verify
--- a/base/xx-verify
+++ b/base/xx-verify
@@ -10,13 +10,12 @@ if [ -z "$XX_VERIFY_NOLOCK" ]; then
 fi
 
 if [ -n "$XX_DEBUG_VERIFY" ]; then
-    set -x
+  set -x
 fi
 
 for l in $(xx-info env); do
   export $l
 done
-
 
 setup() {
   if ! which file >/dev/null 2>/dev/null; then
@@ -44,23 +43,23 @@ files=""
 
 for i in "$@"; do
   case "$i" in
-  "--setup")
-    setup /dev/stderr
-    if [ $# = "1" ]; then exit 0; fi
-    ;;
-  "--static")
-    static=1
-    ;;
-  "--help")
-    usage
-    ;;
-  -*)
-    echo >&2 "invalid flag $i"
-    exit 1
-    ;;
-  *)
-    files=1
-    ;;
+    "--setup")
+      setup /dev/stderr
+      if [ $# = "1" ]; then exit 0; fi
+      ;;
+    "--static")
+      static=1
+      ;;
+    "--help")
+      usage
+      ;;
+    -*)
+      echo >&2 "invalid flag $i"
+      exit 1
+      ;;
+    *)
+      files=1
+      ;;
   esac
 done
 
@@ -88,15 +87,15 @@ for f in "$@"; do
 
   expOS=""
   case "$TARGETOS" in
-  "linux")
-    expOS="ELF"
-    ;;
-  "darwin")
-    expOS="Mach-O"
-    ;;
-  "windows")
-    expOS="MS Windows"
-    ;;
+    "linux")
+      expOS="ELF"
+      ;;
+    "darwin")
+      expOS="Mach-O"
+      ;;
+    "windows")
+      expOS="MS Windows"
+      ;;
   esac
 
   if [ -z "$expOS" ]; then
@@ -112,73 +111,73 @@ for f in "$@"; do
   expArch=""
   expArch2="" # extra check for endianness
   case "$TARGETARCH" in
-  "arm64")
-    case "$TARGETOS" in
-    "linux")
-      expArch="ARM aarch64"
+    "arm64")
+      case "$TARGETOS" in
+        "linux")
+          expArch="ARM aarch64"
+          expArch2="64-bit LSB"
+          ;;
+        "darwin")
+          expArch="arm64"
+          ;;
+        "windows")
+          expArch="Aarch64"
+          ;;
+      esac
+      ;;
+    "amd64")
+      case "$TARGETOS" in
+        "linux")
+          expArch="x86-64"
+          expArch2="64-bit LSB"
+          ;;
+        "darwin")
+          expArch="x86_64"
+          ;;
+        "windows")
+          expArch="x86-64"
+          ;;
+      esac
+      ;;
+    "arm")
+      case "$TARGETOS" in
+        "linux")
+          expArch="ARM,"
+          expArch2="32-bit LSB"
+          ;;
+        "windows")
+          expArch="ARMv7"
+          ;;
+      esac
+      ;;
+    "riscv64")
+      expArch="RISC-V"
       expArch2="64-bit LSB"
       ;;
-    "darwin")
-      expArch="arm64"
-      ;;
-    "windows")
-      expArch="Aarch64"
-      ;;
-    esac
-    ;;
-  "amd64")
-    case "$TARGETOS" in
-    "linux")
-      expArch="x86-64"
+    "ppc64le")
+      expArch="64-bit PowerPC"
       expArch2="64-bit LSB"
       ;;
-    "darwin")
-      expArch="x86_64"
+    "s390x")
+      expArch="IBM S/390"
+      expArch2="64-bit MSB"
       ;;
-    "windows")
-      expArch="x86-64"
+    "mips")
+      expArch="MIPS"
+      expArch2="32-bit MSB"
       ;;
-    esac
-    ;;
-  "arm")
-    case "$TARGETOS" in
-    "linux")
-      expArch="ARM,"
+    "mipsle")
+      expArch="MIPS"
       expArch2="32-bit LSB"
       ;;
-    "windows")
-      expArch="ARMv7"
+    "mips64")
+      expArch="MIPS"
+      expArch2="64-bit MSB"
       ;;
-    esac
-    ;;
-  "riscv64")
-    expArch="RISC-V"
-    expArch2="64-bit LSB"
-  ;;
-  "ppc64le")
-    expArch="64-bit PowerPC"
-    expArch2="64-bit LSB"
-  ;;
-  "s390x")
-    expArch="IBM S/390"
-    expArch2="64-bit MSB"
-  ;;
-  "mips")
-    expArch="MIPS"
-    expArch2="32-bit MSB"
-    ;;
-  "mipsle")
-    expArch="MIPS"
-    expArch2="32-bit LSB"
-    ;;
-  "mips64")
-    expArch="MIPS"
-    expArch2="64-bit MSB"
-    ;;
-  "mips64le")
-    expArch="MIPS"
-    expArch2="64-bit LSB"
-    ;;
+    "mips64le")
+      expArch="MIPS"
+      expArch2="64-bit LSB"
+      ;;
   esac
 
   if [ -z "$expArch" ]; then
@@ -192,17 +191,17 @@ for f in "$@"; do
   fi
 
   if [ -n "$expArch2" ]; then
-  if ! echo $out | grep "$expArch2" >/dev/null; then
-    echo >&2 "file ${f} does not match expected endianness for ${TARGETARCH}: $out"
-    exit 1
-  fi
+    if ! echo $out | grep "$expArch2" >/dev/null; then
+      echo >&2 "file ${f} does not match expected endianness for ${TARGETARCH}: $out"
+      exit 1
+    fi
   fi
 
   if [ -n "$static" ]; then
-  if ! echo $out | grep "statically linked" >/dev/null; then
-    echo >&2 "file ${f} is not statically linked: $out"
-    exit 1
-  fi 
+    if ! echo $out | grep "statically linked" >/dev/null; then
+      echo >&2 "file ${f} is not statically linked: $out"
+      exit 1
+    fi
   fi
 
 done
